"""Inventory data model. One YAML file per host under inventory/hosts/."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import yaml


@dataclass(frozen=True)
class Host:
    name: str
    addr: str
    port: int = 22
    user: str | None = None
    identity_file: str | None = None
    role: str = "personal"
    tags: tuple[str, ...] = field(default_factory=tuple)


def load_hosts(inventory_dir: Path) -> list[Host]:
    """Read every *.yaml / *.yml under inventory_dir and return a list of Host.

    Both extensions are accepted so users can drop in either form (the
    `dots ssh render` help text advertises the *.yml shorthand).
    """
    hosts: list[Host] = []
    yaml_files = sorted(list(inventory_dir.glob("*.yaml")) + list(inventory_dir.glob("*.yml")))
    for yaml_file in yaml_files:
        raw = yaml.safe_load(yaml_file.read_text()) or {}
        hosts.append(
            Host(
                name=raw["name"],
                addr=raw["addr"],
                port=int(raw.get("port", 22)),
                user=raw.get("user"),
                identity_file=raw.get("identity_file"),
                role=raw.get("role", "personal"),
                tags=tuple(raw.get("tags", [])),
            )
        )
    return hosts


def render_ssh_config(hosts: list[Host], role_filter: str | None = None) -> str:
    """Emit OpenSSH config block for the given hosts."""
    lines = [
        "# AUTO-GENERATED by `dots ssh render` — do not edit.",
        f"# Source: dots inventory ({len(hosts)} hosts)",
        "",
    ]
    for h in hosts:
        if role_filter and h.role != role_filter:
            continue
        lines.append(f"Host {h.name}")
        lines.append(f"    HostName {h.addr}")
        if h.port != 22:
            lines.append(f"    Port {h.port}")
        if h.user:
            lines.append(f"    User {h.user}")
        if h.identity_file:
            lines.append(f"    IdentityFile {h.identity_file}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
