"""dots restore — port of lib/restore.sh (chezmoi init + apply only; pkg install stays bash).

Scope-cut per spec §10: this command only handles the chezmoi-related path.
Package-manager bootstrapping (apt/dnf/brew, conda, oh-my-posh, eza, etc.) is
OUT OF P3 SCOPE and stays in bash `~/.files/lib/cli-legacy.sh restore` (NOT
`~/.files/cli restore` — the cli shim now delegates to dots restore which is
also stubbed for the install_essential_tools phase).
"""

from __future__ import annotations

import platform as _platform
import shutil as _shutil
import sys
from pathlib import Path

import click

from acap_dotfiles.core.chezmoi import ChezmoiError, Wrapper, discover_binary
from acap_dotfiles.core.config import DotsConfig
from acap_dotfiles.io.exec import stream


def _is_tty() -> bool:
    """Return True if stdin is a TTY. Wrapped so tests can patch this symbol
    directly (Click's CliRunner replaces sys.stdin, so patching
    `sys.stdin.isatty` does not survive the swap)."""
    return sys.stdin.isatty()


def _platform_data() -> dict[str, str | bool]:
    """Detect platform facts for the non-TTY chezmoi.toml stub.

    Mirrors ``lib/restore.sh::create_default_config`` so chezmoi templates
    that dereference ``.pkgmgr`` / ``.name`` / ``.isWindows`` / ``.hasOp`` /
    ``.isLinux`` / ``.isDarwin`` / ``.isWSL`` / ``.opSignedIn`` / ``.osid`` /
    ``.arch`` / ``.hostname`` / ``.email`` / ``.personal`` don't blow up with
    "missing key" errors during ``chezmoi apply --force``.
    """
    system = _platform.system()
    is_windows = system == "Windows"
    is_darwin = system == "Darwin"
    is_linux = system == "Linux"
    pkgmgr = (
        "winget"
        if is_windows
        else "brew"
        if is_darwin
        else next(
            (m for m in ("apt", "dnf", "yum", "pacman", "zypper") if _shutil.which(m)),
            "unknown",
        )
    )
    has_op = _shutil.which("op") is not None
    return {
        "email": "your-email@example.com",
        "name": "CI Runner",
        "hostname": _platform.node(),
        "personal": False,
        "osid": system.lower(),
        "arch": _platform.machine().lower() or "amd64",
        "isLinux": is_linux,
        "isDarwin": is_darwin,
        "isWindows": is_windows,
        "isWSL": False,
        "pkgmgr": pkgmgr,
        "hasOp": has_op,
        "opSignedIn": False,
    }


def _stub_chezmoi_toml() -> str:
    """Render the auto-generated stub chezmoi.toml body for non-TTY restore.

    Hand-rolled (vs tomli_w) so booleans serialize as bare ``true``/``false``
    rather than quoted strings, matching the bash equivalent's output.
    """
    data = _platform_data()
    lines = [
        "# Auto-generated by `dots restore` non-TTY mode.",
        "# Replace placeholder values before re-running interactively.",
        "[data]",
    ]
    for k, v in data.items():
        if isinstance(v, bool):
            lines.append(f"    {k} = {'true' if v else 'false'}")
        elif isinstance(v, str):
            lines.append(f'    {k} = "{v}"')
        else:
            lines.append(f"    {k} = {v}")
    return "\n".join(lines) + "\n"


@click.command()
@click.option("-f", "--force", is_flag=True, help="Pass --force to chezmoi apply.")
@click.pass_context
def restore(ctx: click.Context, force: bool) -> None:
    """Initialize chezmoi from the source dir and apply dotfiles.

    Equivalent to `chezmoi init <source>` followed by `chezmoi apply`. Use on
    a fresh host (or after a `cli restore --force` clean slate) to lay down
    every managed file. Auto-injects `--force` and writes a stub
    `~/.config/chezmoi/chezmoi.toml` when stdin is non-TTY (CI / SSH `-T`).

    Out of P3 scope: package-manager bootstrap (apt/dnf/brew, conda,
    oh-my-posh, eza). Run `~/.files/lib/cli-legacy.sh restore` first on a
    bare host to install prereqs, then `dots restore`.
    """
    cfg = DotsConfig()
    try:
        binary = discover_binary()
    except ChezmoiError as e:
        click.echo(str(e), err=True)
        sys.exit(2)
    w = Wrapper(binary=binary, dry_run=ctx.obj.get("dry_run", False), source=cfg.home)

    is_tty = _is_tty()
    auto_force = not is_tty

    # Stub chezmoi.toml when non-TTY (chezmoi init prompts otherwise).
    # Wrapper.build_argv already injects --source from cfg.home; we let it own
    # that to avoid double-passing --source on init.
    cfg_dir = Path.home() / ".config" / "chezmoi"
    cfg_path = cfg_dir / "chezmoi.toml"
    if not is_tty and not cfg_path.exists():
        cfg_dir.mkdir(parents=True, exist_ok=True)
        cfg_path.write_text(_stub_chezmoi_toml())

    # init — Wrapper.build_argv prepends --source from cfg.home.
    # Skip in non-TTY when a chezmoi.toml already exists (or was just stubbed):
    # `chezmoi init` re-renders .chezmoi.toml.tmpl which contains
    # promptStringOnce calls that fail with EOF on stdin in non-TTY contexts
    # (CI, SSH `-T` bootstrap). Mirrors legacy lib/restore.sh behavior — the
    # apply step alone is enough once the config stub is in place.
    should_run_init = is_tty or not cfg_path.exists()
    if should_run_init:
        rc = stream(
            w.build_argv(["init"]),
            on_stdout=lambda line: click.echo(line),
            on_stderr=lambda line: click.echo(line, err=True),
        )
        if rc != 0:
            click.echo(f"chezmoi init failed (rc={rc})", err=True)
            sys.exit(rc)

    # apply — auto-inject --force when non-TTY (no prompt path available).
    apply_args = ["apply"]
    if force or auto_force:
        apply_args.append("--force")
    rc2 = stream(
        w.build_argv(apply_args),
        on_stdout=lambda line: click.echo(line),
        on_stderr=lambda line: click.echo(line, err=True),
    )
    sys.exit(rc2)
