"""dots restore — port of lib/restore.sh (chezmoi init + apply only; pkg install stays bash).

Scope-cut per spec §10: this command only handles the chezmoi-related path.
Package-manager bootstrapping (apt/dnf/brew, conda, oh-my-posh, eza, etc.) is
OUT OF P3 SCOPE and stays in bash `~/.files/lib/cli-legacy.sh restore` (NOT
`~/.files/cli restore` — the cli shim now delegates to dots restore which is
also stubbed for the install_essential_tools phase).
"""

from __future__ import annotations

import sys
from pathlib import Path

import click

from acap_dotfiles.core.chezmoi import ChezmoiError, Wrapper, discover_binary
from acap_dotfiles.core.config import DotsConfig
from acap_dotfiles.io.exec import stream


def _is_tty() -> bool:
    """Return True if stdin is a TTY. Wrapped so tests can patch this symbol
    directly (Click's CliRunner replaces sys.stdin, so patching
    `sys.stdin.isatty` does not survive the swap)."""
    return sys.stdin.isatty()


@click.command()
@click.option("-f", "--force", is_flag=True, help="Pass --force to chezmoi apply.")
@click.pass_context
def restore(ctx: click.Context, force: bool) -> None:
    """Initialize chezmoi from the source dir and apply.

    Note: package-manager bootstrapping (apt/dnf/brew, conda, oh-my-posh, eza,
    etc.) is OUT OF P3 SCOPE and stays in bash `~/.files/lib/cli-legacy.sh
    restore`. Run that on a fresh host before `dots restore`.
    """
    cfg = DotsConfig()
    try:
        binary = discover_binary()
    except ChezmoiError as e:
        click.echo(str(e), err=True)
        sys.exit(2)
    w = Wrapper(binary=binary, source=cfg.home)

    is_tty = _is_tty()
    auto_force = not is_tty

    # Stub chezmoi.toml when non-TTY (chezmoi init prompts otherwise).
    # Wrapper.build_argv already injects --source from cfg.home; we let it own
    # that to avoid double-passing --source on init.
    if not is_tty:
        cfg_dir = Path.home() / ".config" / "chezmoi"
        cfg_path = cfg_dir / "chezmoi.toml"
        if not cfg_path.exists():
            cfg_dir.mkdir(parents=True, exist_ok=True)
            cfg_path.write_text(
                "# Auto-generated by `dots restore` non-TTY mode.\n"
                "# Replace placeholder values before re-running interactively.\n"
                "[data]\n"
                '    email = "your-email@example.com"\n'
            )

    # init — Wrapper.build_argv prepends --source from cfg.home.
    rc = stream(
        w.build_argv(["init"]),
        on_stdout=lambda line: click.echo(line),
        on_stderr=lambda line: click.echo(line, err=True),
    )
    if rc != 0:
        click.echo(f"chezmoi init failed (rc={rc})", err=True)
        sys.exit(rc)

    # apply — auto-inject --force when non-TTY (no prompt path available).
    apply_args = ["apply"]
    if force or auto_force:
        apply_args.append("--force")
    rc2 = stream(
        w.build_argv(apply_args),
        on_stdout=lambda line: click.echo(line),
        on_stderr=lambda line: click.echo(line, err=True),
    )
    sys.exit(rc2)
